import { Platform, StyleSheet } from "react-native";

export const setupStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#fdf6ee",
  },
  header: {
    paddingTop: Platform.OS === "ios" ? 64 : 42,
    paddingHorizontal: 20,
    paddingBottom: 18,
    backgroundColor: "#fffaf4",
    borderBottomWidth: 1,
    borderBottomColor: "#f0dcc8",
  },
  kicker: {
    color: "#a07050",
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  title: {
    color: "#2d1a0e",
    fontSize: 24,
    fontWeight: "800",
    marginTop: 4,
  },
  progressTrack: {
    height: 8,
    backgroundColor: "#f0dcc8",
    borderRadius: 999,
    overflow: "hidden",
    marginTop: 16,
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#e8845a",
  },
  content: {
    padding: 20,
    paddingBottom: 120,
  },
  panel: {
    width: "100%",
    maxWidth: 560,
    alignSelf: "center",
  },
  stepTitle: {
    color: "#2d1a0e",
    fontSize: 24,
    fontWeight: "800",
  },
  stepSub: {
    color: "#8a6142",
    fontSize: 14,
    lineHeight: 21,
    marginTop: 8,
    marginBottom: 22,
  },
  field: {
    marginBottom: 16,
  },
  label: {
    color: "#5c351d",
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 8,
  },
  input: {
    minHeight: 52,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#e8d0b8",
    backgroundColor: "#fffaf4",
    color: "#2d1a0e",
    fontSize: 15,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  textArea: {
    minHeight: 108,
    textAlignVertical: "top",
  },
  promptInput: {
    minHeight: 76,
    textAlignVertical: "top",
  },
  photoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  photoSlot: {
    width: "30%",
    minWidth: 96,
    aspectRatio: 0.78,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#e8d0b8",
    borderStyle: "dashed",
    backgroundColor: "#fffaf4",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  photoImage: {
    width: "100%",
    height: "100%",
  },
  photoSlotText: {
    color: "#8a6142",
    fontSize: 13,
    fontWeight: "800",
    textAlign: "center",
  },
  photoBadge: {
    position: "absolute",
    left: 8,
    bottom: 8,
    backgroundColor: "rgba(45, 26, 14, 0.72)",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  photoBadgeText: {
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "800",
  },
  photoRemoveButton: {
    position: "absolute",
    top: 7,
    right: 7,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "rgba(45, 26, 14, 0.72)",
    alignItems: "center",
    justifyContent: "center",
  },
  photoRemoveText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
    lineHeight: 18,
  },
  wrapOptions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 18,
  },
  optionChip: {
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: "#e8d0b8",
    backgroundColor: "#fffaf4",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  optionChipSelected: {
    borderColor: "#e8845a",
    backgroundColor: "#e8845a",
  },
  optionChipText: {
    color: "#5c351d",
    fontWeight: "800",
  },
  optionChipTextSelected: {
    color: "#ffffff",
  },
  heightPicker: {
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#e8d0b8",
    backgroundColor: "#fffaf4",
    padding: 14,
    marginBottom: 18,
  },
  heightHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
  },
  heightValue: {
    color: "#e8845a",
    fontSize: 15,
    fontWeight: "900",
  },
  heightSubLabel: {
    color: "#8a6142",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 8,
    marginBottom: 8,
  },
  heightScroller: {
    gap: 8,
    paddingRight: 8,
  },
  heightChip: {
    minWidth: 64,
    minHeight: 42,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#e8d0b8",
    backgroundColor: "#fdf6ee",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  heightChipSelected: {
    borderColor: "#e8845a",
    backgroundColor: "#e8845a",
  },
  heightChipText: {
    color: "#5c351d",
    fontSize: 14,
    fontWeight: "800",
  },
  heightChipTextSelected: {
    color: "#ffffff",
  },
  segmented: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 18,
  },
  segment: {
    flex: 1,
    minHeight: 48,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#e8d0b8",
    backgroundColor: "#fffaf4",
    alignItems: "center",
    justifyContent: "center",
  },
  segmentSelected: {
    borderColor: "#e8845a",
    backgroundColor: "#e8845a",
  },
  segmentText: {
    color: "#5c351d",
    fontWeight: "800",
  },
  segmentTextSelected: {
    color: "#ffffff",
  },
  agePill: {
    alignSelf: "flex-start",
    backgroundColor: "#fdf0e4",
    borderColor: "#e8d0b8",
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
    marginTop: -6,
    marginBottom: 16,
  },
  ageText: {
    color: "#5c351d",
    fontSize: 13,
    fontWeight: "800",
  },
  error: {
    maxWidth: 560,
    alignSelf: "center",
    color: "#c84b2f",
    fontSize: 13,
    fontWeight: "700",
    marginTop: 4,
  },
  footer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: "row",
    gap: 12,
    padding: 20,
    backgroundColor: "#fffaf4",
    borderTopWidth: 1,
    borderTopColor: "#f0dcc8",
  },
  primaryButton: {
    flex: 2,
    minHeight: 52,
    borderRadius: 14,
    backgroundColor: "#e8845a",
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
  },
  secondaryButton: {
    flex: 1,
    minHeight: 52,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#e8d0b8",
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryButtonText: {
    color: "#5c351d",
    fontSize: 16,
    fontWeight: "800",
  },
  disabledButton: {
    opacity: 0.45,
  },
});
